version: '3'

services:
  
  app:
    restart: always
    build:
      context: .
    ports: 
      - 8000:8000
    env_file: .env
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py initadmin &&
      python manage.py load_dataset &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:10-alpine
    env_file: .env
    volumes:
      - ./db:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    restart: always

  worker:
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    env_file: .env
    depends_on:
      - db
      - redis
      - app