version: '3'

services:
  
  app:
    restart: always
    build:
      context: .
    ports: 
      - 8000:8000
    env_file: .env
    volumes:
      - ./app:/app
    command: >
      sh -c "
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file: .env
    volumes:
      - ./db:/var/lib/postgresql/data/
