# Generated by Django 3.2.13 on 2022-04-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbn', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('all_students', 'All Students'), ('attend_school_outside_district_of_residence', 'Attend school outside district of residence'), ('english_language_learners', 'English Language Learners'), ('poverty', 'Poverty'), ('reside_in_temporary_housing', 'Reside in temporary housing'), ('students_with_disabilities', 'Students with Disabilities')], max_length=255)),
                ('year', models.CharField(max_length=50)),
                ('total_enrollment', models.PositiveIntegerField()),
                ('grade_k', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_1', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_2', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_3', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_4', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_5', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_6', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_7', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_8', models.PositiveIntegerField(blank=True, null=True)),
                ('female', models.PositiveIntegerField(blank=True, null=True)),
                ('male', models.PositiveIntegerField(blank=True, null=True)),
                ('asian', models.PositiveIntegerField(blank=True, null=True)),
                ('black', models.PositiveIntegerField(blank=True, null=True)),
                ('hispanic', models.PositiveIntegerField(blank=True, null=True)),
                ('other', models.PositiveIntegerField(blank=True, null=True)),
                ('white', models.PositiveIntegerField(blank=True, null=True)),
                ('ela_test_takers', models.PositiveIntegerField(blank=True, null=True)),
                ('ela_level_1', models.PositiveIntegerField(blank=True, null=True)),
                ('ela_level_2', models.PositiveIntegerField(blank=True, null=True)),
                ('ela_level_3', models.PositiveIntegerField(blank=True, null=True)),
                ('ela_level_4', models.PositiveIntegerField(blank=True, null=True)),
                ('ela_l3_l4', models.PositiveIntegerField(blank=True, null=True)),
                ('math_test_takers', models.PositiveIntegerField(blank=True, null=True)),
                ('math_level_1', models.PositiveIntegerField(blank=True, null=True)),
                ('math_level_2', models.PositiveIntegerField(blank=True, null=True)),
                ('math_level_3', models.PositiveIntegerField(blank=True, null=True)),
                ('math_level_4', models.PositiveIntegerField(blank=True, null=True)),
                ('math_l3_l4', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['dbn', 'school_name', 'category'],
            },
        ),
    ]
